controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    so_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

so_arm_controller:
  ros__parameters:
    joints:
      - joint_base_rotation_pitch
      - joint_rotation_pitch_upper_arm
      - joint_upper_arm_lower_arm
      - joint_lower_arm_wrist_pitch_roll
      - joint_wrist_pitch_roll_gripper
      - joint_fixed_jaw_moving_jaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false