<package format="2">
  <name>so_5dof_arm100_8j_urdf_sldasm</name>
  <version>1.0.0</version>
  <description>URDF description package for SO 5DOF ARM100 8J</description>
  <author>TODO</author>
  <maintainer email="joshua@email.com"> Joshua Lara </maintainer>
  <license>BSD</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>robot_state_publisher</depend>
  <depend>rviz</depend>
  <depend>joint_state_publisher_gui</depend>
  <depend>gazebo_ros</depend>
  <export>
    <architecture_independent />
  </export>
</package>
